spring:
  application:
    name: MediPartner
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      id-type: assign_id

medi:
  jwt:
    secret: ${MEDI_JWT_SECRET:MediPartner_Secret_Key_For_Jwt_Only_Dev_2025_ChangeMeInProd}
    expire-minutes: 120
  order:
    max-active-orders: 3
    max-active-orders-low-credit: 1
    min-credit-accept: 60
    low-credit-threshold: 80

springdoc:
  swagger-ui:
    path: /swagger-ui.html
