CREATE TABLE service_order (
    id            BIGINT        NOT NULL COMMENT '主键',
    order_no      VARCHAR(32)   NOT NULL COMMENT '订单号',
    user_id       BIGINT        NOT NULL COMMENT '下单用户ID',
    worker_id     BIGINT        DEFAULT NULL COMMENT '接单陪诊师ID',
    amount        DECIMAL(12, 2) NOT NULL COMMENT '服务费(虚拟币)',
    order_status  INT           NOT NULL DEFAULT 10 COMMENT '订单状态: 10待接单 20已接单 30服务中 40待确认 50已完成 60已取消 70异常',
    geo_hash      VARCHAR(32)   DEFAULT NULL COMMENT '用户定位GeoHash',
    service_type  VARCHAR(32)   NOT NULL DEFAULT 'ACCOMPANY' COMMENT '服务类型(扩展预留)',
    symptom_desc  VARCHAR(500)  DEFAULT NULL COMMENT '症状描述',
    city          VARCHAR(64)   DEFAULT NULL COMMENT '就医城市',
    hospital_pref VARCHAR(255)  DEFAULT NULL COMMENT '医院偏好',
    service_time  DATETIME      DEFAULT NULL COMMENT '期望服务时间',
    version       INT           NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    accepted_at   DATETIME      DEFAULT NULL COMMENT '接单时间',
    started_at    DATETIME      DEFAULT NULL COMMENT '开始服务时间',
    finished_at   DATETIME      DEFAULT NULL COMMENT '结束服务时间',
    confirmed_at  DATETIME      DEFAULT NULL COMMENT '确认完成时间',
    created_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_no (order_no),
    KEY idx_user_id (user_id),
    KEY idx_worker_status (worker_id, order_status),
    KEY idx_status (order_status)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '订单主表';
